spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zelda_product
    username: master
    password: password

redis:
  enabled: false

kafka:
  enabled: false

logging:
  level:
    com.mediquitous: DEBUG
